<template>
  <div class="collapse py-2" id="collapseTarget">
    This is the toggle-able content!
  </div>
  <nav class="navbar navbar-expand-lg navbar-dark b-2">
    <div class="container-fluid">
      <div class="navbar-brand me-5">
        <div><a :href="base_url">Live shopping UI</a></div>
        <div class="ms-4" style="margin-top: -10px">
          <span class="fs-6 mt-0 pt-0">backend powered by </span>
          <a target="blank" href="https://agoston.io">
            <img
              src="@/assets/img/logo_horizontal_x300.png"
              alt=""
              width="60"
            />
          </a>
        </div>
      </div>

      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarText"
        aria-controls="navbarText"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-3 mb-lg-0">
          <li class="nav-item">
            <a
              class="nav-link text-light"
              aria-current="page"
              href="https://github.com/niolap/live-shopping-ui"
              target="_blank"
              ><font-awesome-icon :icon="['fab', 'github']" /> Fork me</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link text-light"
              aria-current="page"
              href="https://picsum.photos/"
              target="_blank"
              ><font-awesome-icon :icon="['fas', 'photo-video']" /> Media
              generated by Picsum</a
            >
          </li>
        </ul>
        <span class="navbar-text">Share <SocialNetwork /></span>
      </div>
    </div>
  </nav>
</template>

<script>
import SocialNetwork from "./SocialNetwork.vue";
export default {
  name: "Menu",
  components: {
    SocialNetwork,
  },
  data() {
    return {
      base_url: process.env.BASE_URL,
    };
  },
};
</script>
