mutation createChatMessage ($broadcastId: Int!,$message: String!) {
  createChat(input: {chat: {broadcastId: $broadcastId, content: $message}}) {
    chat {
      id
      content
      createdAt
    }
  }
}
