query oneChat($broadcastId: Int!) {
  oneChat: query {
    currentTs
    chats(condition: {broadcastId: $broadcastId}) {
      nodes {
        content
        createdAt
        id
        user {
          username
        }
      }
    }
  }
}
