subscription oneChat($topic: String!, $broadcast_id: Int!) {
  listen(topic: $topic) {
    query {
      oneChat: chats(condition: {broadcastId: $broadcast_id}, orderBy: CREATED_AT_ASC, last: 20) {
        nodes {
          content
          createdAt
          id
          user {
            username
          }
        }
      }
    }
  }
}

