subscription oneChat($topic: String!, $broadcastId: Int!) {
  listen(topic: $topic) {
    oneChat: query {
      currentTs
      chats(condition: {broadcastId: $broadcastId}) {
        nodes {
          content
          createdAt
          id
          user {
            username
          }
        }
      }
    }
  }
}

